#
# Copy in some params files and stuff
#

moby2_deps:
	-rm -r _moby2/params
        #cp -r $(MOBY2_DIR)/data/params _moby2/

install: html
	-mkdir _install _install/html/
	cp -r _build/html/* _install/html/

.PHONY: moby2_deps moby2_params
